-- premake/helpers.lua -- shared paths, glob, and output-dir helpers.
-- (Slang shader compilation lives in premake/slang.lua.)
-- All helpers are global so the dofile'd sub-scripts can use them directly.

DEPS_EXTERN  = ROOT .. "/HPL2/extern"
DEPS_SOURCES = DEPS_EXTERN   -- merged: submodules + vendored sources share one dir
CONFIG_DIR   = ROOT .. "/premake/config"   -- pre-generated, per-platform config headers
BUILD_OUT    = "%{wks.location}"           -- build-premake/

-- Public headers for the in-tree dependencies. Replaces the old aggregated
-- HPL2/dependencies/include tree (removed): submodule libs (ogg, vorbis) expose
-- their own include/, vendored libs (DevIL, Newton, OALWrapper, freealut) expose
-- headers next to their sources. openal-soft and SDL headers come separately via
-- link_openal() / link_sdl2().
function deps_public_includes()
    includedirs {
        CONFIG_DIR .. "/common",            -- generated <ogg/config_types.h>
        DEPS_EXTERN .. "/ogg/include",      -- <ogg/*.h>
        DEPS_EXTERN .. "/vorbis/include",   -- <vorbis/*.h>
        DEPS_SOURCES .. "/DevIL/include",   -- <IL/il.h>
        DEPS_SOURCES .. "/Newton",          -- <Newton.h>
        DEPS_SOURCES .. "/OpenAL",          -- "OpenAL/OAL_*.h" (OALWrapper public)
        DEPS_SOURCES .. "/freealut",        -- <AL/EFX-Util.h>, <AL/xram.h>
        DEPS_SOURCES .. "/freealut/AL",     -- <alut.h>
    }
end

-- Runtime artifacts + shared libs go to build-premake/amnesia/<config>/
-- alongside the game; the optional subdir (e.g. "libs") nests under it.
--
-- The second argument is the product context when the first argument is the
-- legacy subdirectory. For new call sites, runtime_dir(product, subdir) is
-- also accepted. Keeping both forms lets external.lua retain its existing
-- runtime_dir("libs") calls while products can opt into an isolated runtime.
function runtime_context(product, target_layout)
    product = product or "amnesia"
    if product == "" then product = "amnesia" end
    if target_layout == "tests" or product == "tests" then return "tests" end
    if product == "game" then return "amnesia" end
    return product
end

local function is_runtime_subdir(value)
    if not value or value == "" then return true end
    return value == "libs" or value:match("^compiled_shaders/") ~= nil or
        value:match("^licenses/") ~= nil
end

function runtime_dir(product_or_subdir, subdir_or_product)
    local product, subdir
    if type(product_or_subdir) == "table" then
        product = product_or_subdir.product or product_or_subdir.context
        subdir = product_or_subdir.subdir
    elseif subdir_or_product ~= nil then
        if is_runtime_subdir(product_or_subdir) then
            -- Backwards-compatible extension: runtime_dir(subdir, product).
            subdir, product = product_or_subdir, subdir_or_product
        else
            -- Preferred form: runtime_dir(product, subdir).
            product, subdir = product_or_subdir, subdir_or_product
        end
    elseif is_runtime_subdir(product_or_subdir) then
        product, subdir = "amnesia", product_or_subdir
    else
        product, subdir = product_or_subdir, ""
    end

    product = runtime_context(product)
    local root = product == "tests" and (BUILD_OUT .. "/tests/%{cfg.buildcfg}") or
        (BUILD_OUT .. "/" .. product .. "/%{cfg.buildcfg}")
    if subdir and subdir ~= "" then root = root .. "/" .. subdir end
    return root
end

-- Per-project build-config stamp. make's .d files track headers, not include
-- paths or defines, so switching a project's defines or AngelScript version
-- would otherwise reuse objects built for the old configuration (ABI mismatch).
-- The stamp header is force-included into every TU of the project and only
-- rewritten when the key changes, so a changed key rebuilds the whole project.
-- Its static archive is removed too: `ar -rcs` never drops stale members.
local CONFIG_STAMP_DIR = ROOT .. "/build-premake/config-stamp"

function config_stamp(name, key_parts)
    local parts = {}
    for i, p in ipairs(key_parts) do
        -- Repo-relative so moving the checkout does not force a rebuild.
        if p:sub(1, #ROOT) == ROOT then p = p:sub(#ROOT + 2) end
        parts[i] = p
    end
    local key = table.concat(parts, ";")
    local path = CONFIG_STAMP_DIR .. "/" .. name .. ".h"
    local expected = "// Generated by premake/helpers.lua config_stamp(). Do not edit.\n" ..
                     "// " .. key .. "\n"

    local current_file = io.open(path, "rb")
    local current = current_file and current_file:read("*a") or nil
    if current_file then current_file:close() end
    if current ~= expected then
        os.mkdir(CONFIG_STAMP_DIR)
        local f = assert(io.open(path, "wb"))
        f:write(expected)
        f:close()
        if current ~= nil then
            for _, lib in ipairs(os.matchfiles(ROOT .. "/build-premake/lib/**/lib" .. name .. ".a")) do
                os.remove(lib)
            end
            for _, lib in ipairs(os.matchfiles(ROOT .. "/build-premake/lib/**/" .. name .. ".lib")) do
                os.remove(lib)
            end
        end
    end
    -- Force-include by bare name through the include path: premake rewrites a
    -- path relative to the project location, which MSVC's /FI cannot resolve.
    includedirs { CONFIG_STAMP_DIR }
    forceincludes { name .. ".h" }
end

-- Headers generated by build-time tools live outside the source tree. Keep the
-- include registration conditional so Vulkan/Linux builds never depend on a
-- D3D12-only generated directory.
function generated_includes()
    if os.target() == "windows" and _OPTIONS["with-d3d12"] == "yes" then
        includedirs { BUILD_OUT .. "/generated/%{cfg.buildcfg}" }
    end
end

-- Standard output layout for a target. kind: "runtime" (exe / shared lib that
-- must sit next to Amnesia) or "static" (intermediate static lib).
function set_output(kind, product)
    if type(kind) == "table" then
        product = kind.product or kind.context
        kind = kind.kind
    elseif kind ~= "runtime" and kind ~= "static" and
        (product == "runtime" or product == "static") then
        kind, product = product, kind
    end
    objdir (BUILD_OUT .. "/obj/%{prj.name}/%{cfg.buildcfg}")
    if kind == "runtime" then
        targetdir (runtime_dir(product or "amnesia", ""))
        -- The engine resolves config/resources relative to the working dir.
        -- Windows developers set ATDD_DIR to the game install/data directory.
        filter "system:windows"
            debugdir "$(ATDD_DIR)"
        filter "system:not windows"
            debugdir (runtime_dir(product or "amnesia", ""))
        filter {}
    else
        targetdir (BUILD_OUT .. "/lib/%{cfg.buildcfg}")
    end
end

-- glob(patterns) -> expands a list of ROOT-relative or absolute matchfiles
-- patterns into a flat list; patterns with no matches contribute no files.
function glob(patterns)
    local out = {}
    for _, p in ipairs(patterns) do
        for _, f in ipairs(os.matchfiles(p)) do
            table.insert(out, f)
        end
    end
    return out
end

-- MathLib is header-only. Consumers call mathlib_use() to pull in its include dir.
--
-- On Linux/x86_64 ml.h falls back to ML_INTRINSIC_LEVEL = SSE3 (no __SSE4_2__ macro).
-- That level's SSE4.1 emulation (emu_mm_dp_ps) is built from the SSE3 intrinsic
-- _mm_hadd_ps, which GCC will not inline unless SSSE3 is enabled at the target. The
-- x86_64 baseline is only SSE2, so we enable it explicitly with -mssse3 (SSSE3 -- NOT
-- -msse4.2). -mssse3 makes the intrinsics compile WITHOUT defining __SSE4_2__, so the
-- intrinsic level stays SSE3 and the math is bit-identical to the reference build.
-- Do NOT use -msse4.2: it bumps ML_INTRINSIC_LEVEL to SSE4 and diverged the renderer's
-- vector/matrix math (culling, decal projection) -> missing meshes/decals.
-- MSVC defines ML_INTRINSIC_LEVEL=1 via premake5.lua.
function mathlib_use()
    includedirs { DEPS_EXTERN .. "/MathLib" }
    filter "toolset:gcc or clang"
        buildoptions { "-mssse3" }
    filter {}
end

-- fmt is built as a static lib (premake/deps/fmt.lua); consumers call fmt_use() for its
-- include dir. The FMT_USE_EXCEPTIONS define must match the one the library was built with:
-- FMT_THROW is expanded inside fmt's inline/template code, so a lib/consumer disagreement
-- is a silent ODR violation rather than a compile error. See premake/deps/fmt.lua.
-- FMT_UNICODE must match too, and there it is a hard static_assert in fmt's base.h rather
-- than a silent mismatch: the engine is built characterset "MBCS" without /utf-8.
function fmt_use()
    includedirs { DEPS_EXTERN .. "/fmt/include" }
    filter "toolset:gcc or clang"
        defines { "FMT_USE_EXCEPTIONS=0" }
    filter "system:windows"
        defines { "FMT_UNICODE=0" }
    filter {}
end

-- Vulkan headers + VMA are header-only. Also emit the platform surface defines:
-- volk is compiled here as a plain premake project, so nothing propagates them
-- to its consumers automatically, and the
-- engine's surface-creation code (RISwapchain.cpp) is #ifdef-gated on
-- VK_USE_PLATFORM_*_KHR -- without the define here the surface is never created
-- and the first vkGetPhysicalDeviceSurfaceSupportKHR call dereferences garbage.
function vulkan_includes()
    includedirs {
        DEPS_EXTERN .. "/Vulkan-Headers/include",
        DEPS_EXTERN .. "/VulkanMemoryAllocator/include",
        DEPS_EXTERN .. "/volk",
    }
    vulkan_platform_defines()
end

-- Per-platform Vulkan surface defines (volk's VOLK_STATIC_DEFINES equivalent).
function vulkan_platform_defines()
    filter "system:windows"
        defines { "VK_USE_PLATFORM_WIN32_KHR" }
    filter "system:linux"
        if _OPTIONS["graphics-x11"] ~= "off" then
            defines { "VK_USE_PLATFORM_XLIB_KHR" }
        end
        if _OPTIONS["graphics-wayland"] ~= "off" then
            defines { "VK_USE_PLATFORM_WAYLAND_KHR" }
        end
    filter {}
end

-- D3D12 Memory Allocator is a source dependency: the library has no import
-- library of its own and is built once into the D3D12-enabled HPL2 target.
function d3d12ma_includes()
    if os.target() == "windows" and _OPTIONS["with-d3d12"] == "yes" then
        includedirs { D3D12MA_ROOT .. "/include" }
    end
end

-- BuildID source/header. These files are checked into the tree and are used
-- as-is; add the committed per-platform source + header to the file list.
function buildid(idname, dir)
    local suffix = os.target() == "windows" and "Win32" or "Linux"
    files {
        dir .. "/BuildID_" .. idname .. "_" .. suffix .. ".cpp",
        dir .. "/BuildID_" .. idname .. ".h",
    }
end

CMAKE = _OPTIONS["cmake"] or "cmake"

-- Link the engine + its full dependency set into a final executable. premake
-- does NOT transitively propagate a static library's links to consumers, so
-- every executable (Amnesia, editors, MshConverter) must link the whole set.
-- linkgroups handles the circular static-lib references (vorbis<->ogg, etc.).
function link_engine(target_layout, product)
    if type(target_layout) == "table" then
        product = target_layout.product or target_layout.context
        target_layout = target_layout.target_layout or target_layout.layout
    elseif product == nil and target_layout ~= nil and
        target_layout ~= "game" and target_layout ~= "tests" then
        -- A lone non-layout argument is the convenient product form:
        -- link_engine("tools") means a game-layout link for the tools runtime.
        product, target_layout = target_layout, "game"
    elseif product == "game" or product == "tests" then
        -- Also accept link_engine(product, target_layout).
        target_layout, product = product, target_layout
    end
    target_layout = target_layout or "game"
    product = runtime_context(product, target_layout)
    local dependency_product = target_layout == "tests" and "amnesia" or product
    -- AMFP links its own engine build; consumer TUs need the same define so
    -- they see the same class layouts as the library.
    local engine_lib, angelscript_lib = "HPL2", "AngelScript"
    if product == "amfp" then
        engine_lib, angelscript_lib = "HPL2_AMFP", "AngelScript_AMFP"
        defines { "AMFP" }
    end
    links {
        engine_lib, "OALWrapper", angelscript_lib, "Newton", "tinyxml2", "fmt",
        "vorbisfile", "vorbis", "ogg", "freealut",
        "zlib", "volk", "IL", "png", "jpeg",
    }
    if os.target() == "windows" and _OPTIONS["with-d3d12"] == "yes" then
        links { "D3D12MA" }
    end
    link_sdl2(dependency_product)
    link_openal(dependency_product)
    link_nrd(target_layout, dependency_product)
    link_fsr(target_layout, dependency_product)
    link_xess(target_layout, dependency_product)
    if target_layout == "tests" then
        link_test_runtime_rpath(dependency_product)
    end
    memory_consumer()
    memory_rebuild_consumer()
    filter "system:linux"
        links { "pthread", "dl" }
    filter "system:windows"
        -- Static SDL2/openal-soft do not bring their CMake target dependency
        -- lists with them, so final Windows executables link the Win32 libs here.
        links {
            "kernel32",
            "setupapi",
            "winmm",
            "imm32",
            "version",
            "cfgmgr32",
            "ole32",
            "oleaut32",
            "uuid",
            "advapi32",
            "user32",
            "gdi32",
            "shell32",
            "avrt",
            "dinput8",
        }
        if _OPTIONS["with-d3d12"] == "yes" then
            links { "d3d12", "dxgi", "dxguid" }
            link_agility_runtime(target_layout, product)
        end
        if _OPTIONS["with-tracy"] == "yes" then
            links { "ws2_32", "dbghelp" }   -- TracyClient (network + symbol resolution)
        end
    filter "toolset:gcc or clang"
        linkgroups "On"
    filter {}
end
