-- Mode-safe output wiring for the production memory configuration.
--
-- The memory option changes both the source list and the ABI of the HPL2
-- facade.  Keep the two configurations in different object/archive trees so
-- a re-generated makefile can never reuse an object or an archive member from
-- the other configuration.  Consumers also get a small generated source;
-- changing its contents makes an ordinary incremental build relink them.

local MEMORY_REBUILD_DIR = ROOT .. "/build-premake/memory-rebuild"
local MEMORY_MODE_STAMP = MEMORY_REBUILD_DIR .. "/memory_mode_stamp.cpp"

local function memory_rebuild_mode(enabled)
    if enabled == nil then enabled = memory_tracking_enabled() end
    return enabled and "yes" or "no"
end

local function memory_rebuild_stamp(mode)
    local expected = [[// Generated by premake/memory_rebuild.lua. Do not edit.
extern "C" const char hpl_memory_build_mode_stamp[] = "]] .. mode .. [[";
]]

    local current_file = io.open(MEMORY_MODE_STAMP, "rb")
    local current = current_file and current_file:read("*a") or nil
    if current_file then current_file:close() end
    if current == expected then return end

    -- os.mkdir is used instead of a shell command so paths containing spaces
    -- remain valid on all Premake hosts.  Premake creates missing parents.
    os.mkdir(MEMORY_REBUILD_DIR)
    local stamp_file = assert(io.open(MEMORY_MODE_STAMP, "wb"))
    stamp_file:write(expected)
    stamp_file:close()
end

-- Call from the HPL2 project after memory_engine().  The archive is kept in a
-- mode-specific directory as well as its objects; this is required because
-- `ar -rcs` does not remove members which disappeared from the source list.
function memory_rebuild_engine(enabled)
    local mode = memory_rebuild_mode(enabled)
    objdir(BUILD_OUT .. "/obj/%{prj.name}/memory-" .. mode .. "/%{cfg.buildcfg}")
    targetdir(BUILD_OUT .. "/lib/memory-" .. mode .. "/%{cfg.buildcfg}")
end

-- Call from each production final executable after memory_consumer().  The
-- stamp is intentionally not added to standalone or explicit memory tests;
-- callers opt into this helper only for production consumers.
function memory_rebuild_consumer(enabled)
    local mode = memory_rebuild_mode(enabled)
    memory_rebuild_stamp(mode)
    objdir(BUILD_OUT .. "/obj/%{prj.name}/memory-" .. mode .. "/%{cfg.buildcfg}")
    files { MEMORY_MODE_STAMP }
end

