name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure Cache
        shell: bash
        run: |
          echo "ACTIONS_CACHE_URL=$ACTIONS_CACHE_URL" >> "$GITHUB_ENV"
          echo "ACTIONS_RUNTIME_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake libdevil-dev mesa-common-dev libglew-dev libxmu-dev libfltk1.3-dev libxi-dev libgl-dev libx11-dev libxft-dev libxext-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libvulkan-dev vulkan-tools glslang-tools
      - name: Configure
        run: |
          cd ${{ github.workspace }}
          cmake ${{ github.workspace }} -DVCPKG_INSTALL_OPTIONS="--binarysource=clear\;x-gha,readwrite" -G Ninja
      - name: Build
        run: |
          cd ${{ github.workspace }}
          ninja
      - name: Package Amnesia
        working-directory: .${{ github.workspace }}/build
        run: tar -czvf ../Amnesia-x86-64-Debug.tar.gz * --exclude *.a
      - name: Upload Amnesia artifact
        uses: actions/upload-artifact@v3
        with:
          name: amnesia-x86-64-debug
          path: Amnesia-x86-64-Debug.tar.gz

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure Cache
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "ACTIONS_CACHE_URL=$ACTIONS_CACHE_URL"
          Add-Content -Path $env:GITHUB_ENV -Value "ACTIONS_RUNTIME_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Configure
        run: |
          mkdir ${{ github.workspace }}\build && cd ${{ github.workspace }}\build
          cmake ${{ github.workspace }} -DVCPKG_INSTALL_OPTIONS="--binarysource=clear\;x-gha,readwrite" -DCMAKE_BUILD_TYPE:STRING=Release -DAMNESIA_GAME_DIRECTORY:STRING='' -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: |
          cd ${{ github.workspace }}\build
          msbuild ALL_BUILD.vcxproj /property:Configuration=Debug
      - name: Package Amnesia
        working-directory: ./build
        run: 7z a ..\win-x86-64-Debug.zip * '-xr!*.exp' '-xr!*.lib'
      - name: Upload Amnesia artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-x86-64-Debug
          path: win-x86-64-Debug.zip