name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get install cmake libdevil-dev
      - name: Configure
        run: |
          mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
          cmake $GITHUB_WORKSPACE
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/build
          make