name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tagged Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libdevil-dev mesa-common-dev libxmu-dev libxi-dev libgl-dev libx11-dev libxft-dev libxext-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libglu1-mesa-dev ninja
      - name: Configure
        run: |
          mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/build
          ninja install
      - name: Zipping
        run: |
          cd $GITHUB_WORKSPACE/build
          zip -r Amnesia_linux_x68_64.zip bin/Amnesia
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          draft: true
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $GITHUB_WORKSPACE/build/Amnesia_linux_x68_64.zip
          asset_name: Amnesia_linux_x68_64.zip
          asset_content_type: application/zip
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
